lib/libwamr: Moved wamr to musl
unikraft/app-wamr pull request #5
Opened 2023-07-15 13:21 UTC by R0mbertus

This PR addresses issue #3 by adding the `Makefile`, `Makefile.uk` and `.gitignore`, and also changes to `kraft.yaml` and updated the `README.md.

2023-07-15 14:22 UTC, RaduNichita requested changes
Nice work @R0mbertus :medal_sports: !

Please see my comments.

2023-07-15 14:22 UTC, RaduNichita commented on Makefile
> +	@$(MAKE) -C $(UK_ROOT) A=$(PWD) L=$(LIBS) $(MAKECMDGOALS)
Please add a newline at the end of the file

2023-07-15 14:22 UTC, RaduNichita commented on README.md
> +buf ptr: 0x400002a8
Why do you have these lines in the output?

2023-07-15 14:23 UTC, RaduNichita requested changes
Please change the commit to "app-wamr: Port application to musl"

2023-07-15 15:01 UTC, R0mbertus commented on Makefile
> +	@$(MAKE) -C $(UK_ROOT) A=$(PWD) L=$(LIBS) $(MAKECMDGOALS)
Added in latest commit.

2023-07-15 15:02 UTC, R0mbertus commented on README.md
> +buf ptr: 0x400002a8
The `main.wasm` file is compiled from the hello-world app-sample [here](https://github.com/bytecodealliance/wasm-micro-runtime/blob/bc762fe9e2cf2d26a0cde42931c4b6ed79860047/core/iwasm/app-samples/hello-world/main.c), which prints these lines.

2023-07-15 15:03 UTC, R0mbertus commented
Addressed requested changes

2023-07-17 12:55 UTC, StefanJum requested changes
Looks great @R0mbertus, please wrap you commit message to ~80 characters per line, then I'll approve it.

2023-07-25 18:56 UTC, StefanJum approved these changes
All good, thanks.

Reviewed-by: Stefan Jumarea <stefanjumarea02@gmail.com>

2023-07-25 21:25 UTC, RaduNichita requested changes
All good also from my side.

Reviewed-by: Radu Nichita <radunichita99@gmail.com>

2023-07-25 21:25 UTC, RaduNichita approved these changes

2023-08-05 06:39 UTC, razvand approved these changes
Approved-by: Razvan Deaconescu <razvand@unikraft.io>

2023-08-09 10:17 UTC, closed without merging