Update setup for developer-centric scripts
unikraft/app-wamr pull request #7
Opened 2023-10-14 10:20 UTC by razvand

Update setup to include scripts for building and running. Restructure contents to use the `workdir/` directory as the directory to store repository clones and build output; use `defconfigs/` to store default configuration files.

2023-10-17 10:32 UTC, StefanJum requested changes
See the comments.
Besides those, the main file does not load properly.
It gives a `magic header not detected` error on initrd and a `did not select --repl nor -initrd mode!` warning on 9pfs.

The way `lib-wamr` works now, it expects the actual main file (not a cpio archive) to be passed as an initrd, without mounting it as a filesystem. So it would be `CONFIG_LIBVFSCORE_AUTOMOUNT_ROOTFS=n` in the config files, and the run command should be `qemu-system-x86_64 -kernel build/wamr_qemu-x86_64 -initrd main.wasm  -nographic`.

This means the `9pfs`-`initrd` separation is no longer relevant. Also this might not work with the `generate.py` script, we might want to add some way of configuring extra arguments to be passed to the `qemu` run command.

2023-10-17 10:32 UTC, StefanJum commented on README.md
> +     The layout of the `workdir/` directory should look something like this:
```suggestion
```console
     The layout of the `workdir/` directory should look something like this:
```

2023-10-17 10:32 UTC, StefanJum commented on README.md
> +./scripts/run/qemu-x86_64-9pfs-interp.sh
```suggestion
./scripts/run/qemu-x86_64-9pfs.sh
```

2023-10-20 12:17 UTC, razvand commented
@StefanJum , this relies on [`lib-wamr` PR #9](https://github.com/unikraft/lib-wamr/pull/9).

2023-10-20 13:25 UTC, StefanJum commented
@razvand does [`lib-wamr`#9](https://github.com/unikraft/lib-wamr/pull/9) works for you? I don't get the errors anymore but the file is not executed. The application just closes after printing the Unikraft banner.
I can look into it, just want to make sure if it's something wrong on my config.

2023-10-20 13:36 UTC, razvand commented
> @razvand does [`lib-wamr`#9](https://github.com/unikraft/lib-wamr/pull/9) works for you? I don't get the errors anymore but the file is not executed. The application just closes after printing the Unikraft banner. I can look into it, just want to make sure if it's something wrong on my config.

lemme retry

2023-10-20 14:42 UTC, razvand commented
> > @razvand does [`lib-wamr`#9](https://github.com/unikraft/lib-wamr/pull/9) works for you? I don't get the errors anymore but the file is not executed. The application just closes after printing the Unikraft banner. I can look into it, just want to make sure if it's something wrong on my config.
> 
> lemme retry

@StefanJum , I've retried. I used `lib-wamr` in `workdir/libs/` checked out at PR #9. And I tested both with initrd and 9pfs. It all works:

```console
./scripts/generate.py
./scripts/build/make-qemu-x86_64-9pfs.sh
./scripts/run/qemu-x86_64-9pfs.sh
./scripts/build/make-qemu-x86_64-initrd.sh
./scripts/run/qemu-x86_64-initrd.sh
```

2023-10-20 15:35 UTC, StefanJum approved these changes
All good, thanks.

Reviewed-by: Stefan Jumarea <stefanjumarea02@gmail.com>
Approved-by: Stefan Jumarea <stefanjumarea02@gmail.com>

2023-10-20 15:54 UTC, merged